# =============================================================================
# AI Metrics Dashboard - Kubernetes Manifests
# 
# Prerequisites:
#   1. Create the secret first:
#      kubectl create secret generic ai-metrics-dashboard-secret \
#        --from-literal=MONGODB_URI='mongodb://...' \
#        --from-literal=MONGODB_DB_NAME='your-db-name' \
#        --from-literal=DASHBOARD_PASSWORD='your-secure-password' \
#        --from-literal=SESSION_SECRET='your-32-char-random-secret'
#
#   2. Apply the manifests:
#      kubectl apply -f kubernetes.yaml
#
# =============================================================================

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-metrics-dashboard-config
  labels:
    app: ai-metrics-dashboard
    app.kubernetes.io/name: ai-metrics-dashboard
    app.kubernetes.io/component: config
data:
  # Set BASE_URL if running behind a reverse proxy/ingress with path prefix
  # Leave empty if using root path
  NEXT_PUBLIC_BASE_PATH: ""
  NEXT_PUBLIC_API_BACKEND_BASE_URL_NODE: "/api"
  NODE_ENV: "production"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-metrics-dashboard
  labels:
    app: ai-metrics-dashboard
    app.kubernetes.io/name: ai-metrics-dashboard
    app.kubernetes.io/component: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-metrics-dashboard
  template:
    metadata:
      labels:
        app: ai-metrics-dashboard
        app.kubernetes.io/name: ai-metrics-dashboard
      annotations:
        # Force rolling update when config changes
        checksum/config: "{{ include (print $.Template.BasePath \"/configmap.yaml\") . | sha256sum }}"
    spec:
      # Security context for pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault

      # Service account (create if needed for RBAC)
      serviceAccountName: default
      automountServiceAccountToken: false

      containers:
        - name: ai-metrics-dashboard
          image: your-registry/ai-metrics-dashboard:latest  # Replace with your image
          imagePullPolicy: Always
          
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          # Environment variables from ConfigMap
          envFrom:
            - configMapRef:
                name: ai-metrics-dashboard-config

          # Sensitive environment variables from Secret
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ai-metrics-dashboard-secret
                  key: MONGODB_URI
            - name: MONGODB_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ai-metrics-dashboard-secret
                  key: MONGODB_DB_NAME
            - name: DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-metrics-dashboard-secret
                  key: DASHBOARD_PASSWORD
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: ai-metrics-dashboard-secret
                  key: SESSION_SECRET
                  optional: true

          # Resource limits and requests
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # Security context for container
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          # Volume mounts for read-only filesystem
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nextjs-cache
              mountPath: /app/.next/cache

          # Liveness probe - is the container alive?
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness probe - is the container ready to serve traffic?
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # Startup probe - for slow starting containers
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

      # Volumes for read-only root filesystem
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nextjs-cache
          emptyDir: {}

      # Topology spread for high availability
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: ai-metrics-dashboard

      # Pod disruption budget reference
      # Ensure at least one pod is always available during node maintenance

---
# Service - ClusterIP for internal access
apiVersion: v1
kind: Service
metadata:
  name: ai-metrics-dashboard
  labels:
    app: ai-metrics-dashboard
    app.kubernetes.io/name: ai-metrics-dashboard
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: ai-metrics-dashboard

---
# Service - NodePort for external access (optional, use if no Ingress)
apiVersion: v1
kind: Service
metadata:
  name: ai-metrics-dashboard-nodeport
  labels:
    app: ai-metrics-dashboard
    app.kubernetes.io/name: ai-metrics-dashboard
    app.kubernetes.io/component: service-external
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30080  # Fixed NodePort (30000-32767 range)
  selector:
    app: ai-metrics-dashboard

---
# Pod Disruption Budget - ensure high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-metrics-dashboard-pdb
  labels:
    app: ai-metrics-dashboard
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-metrics-dashboard

---
# Horizontal Pod Autoscaler (optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-metrics-dashboard-hpa
  labels:
    app: ai-metrics-dashboard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-metrics-dashboard
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# NetworkPolicy - restrict traffic (optional, requires network plugin support)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-metrics-dashboard-network-policy
  labels:
    app: ai-metrics-dashboard
spec:
  podSelector:
    matchLabels:
      app: ai-metrics-dashboard
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
    # Allow traffic from same namespace
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow outbound to MongoDB (adjust CIDR as needed)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 27017

---
# Ingress (optional, for nginx ingress controller)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-metrics-dashboard-ingress
  labels:
    app: ai-metrics-dashboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-connections: "5"
spec:
  ingressClassName: nginx
  rules:
    - host: metrics.example.com  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-metrics-dashboard
                port:
                  number: 80
  tls:
    - hosts:
        - metrics.example.com  # Replace with your domain
      secretName: ai-metrics-dashboard-tls  # TLS secret
